### ISSUE TITLE
Problem running on rubygems 1.3.5?

### ISSUE THREAD

**Issue by nandub** [mojombo/ernie#2]
I getting the following error when I try to run the calc.rb example

Executed:
ernie -d -p 9999 -n 10 -h calc.rb
then
require 'bertrpc'
svc = BERTRPC::Service.new('localhost', 9999)
svc.call.calc.add(1, 2)

NameError: uninitialized constant BERT::Encode::StringIO
    from /usr/local/lib/ruby/gems/1.9.1/gems/bert-1.1.0/lib/bert/encode.rb:12:in `encode'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bert-1.1.0/lib/bert/encoder.rb:9:in`encode'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bert-1.1.0/lib/bert/bert.rb:3:in `encode'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bertrpc-1.1.0/lib/bertrpc/encodes.rb:4:in`encode_ruby_request'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bertrpc-1.1.0/lib/bertrpc/action.rb:14:in `execute'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bertrpc-1.1.0/lib/bertrpc/mod.rb:11:in`method_missing'
    from (irb):4
    from /usr/local/bin/irb:12:in `<main>' 

Environment:
- RUBYGEMS VERSION: 1.3.5
- RUBY VERSION: 1.9.1 (2009-07-16 patchlevel 243) [i686-linux]
- INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/1.9.1
- RUBYGEMS PREFIX: /usr/local/lib/ruby/gems/1.9.1/gems/rubygems-update-1.3.5

Linux eratos 2.6.28-15-generic #52-Ubuntu SMP Wed Sep 9 10:49:34 UTC 2009 i686 GNU/Linux

**Comment by mojombo** [comment]
This is a bug in the bert gem. I've fixed it in 8df4e3d81d98fa5ec3e9200c74d0021eee66c31e and it will go out in the next set of releases.
