### ISSUE TITLE
Ernie::expose

### ISSUE THREAD

**Issue by rtomayko** [mojombo/ernie#3]
Ernie adds some syntax for defining RPC modules and functions:

```
mod(:math) do
  fun(:sum) { |vals|
    vals.inject(0) { |x,y| x + y }
  }

  fun(:avg) { |vals|
    vals.inject(0) { |x,y| x + y } / vals.size.to_f
  }
end
```

I'd like to be able to decouple my server side funs from Ernie entirely:

```
module MathRPC
  def sum(vals)
    vals.inject(0) { |x,y| x + y }
  end

  def avg(vals)
    sum(vals) / vals.size.to_f
  end
end

Ernie.expose :math, MathRPC
```

Benefits to this approach:
- I can test the MathRPC implementation without even needing to load the ernie library. Just strap it onto an object and call the methods directly.
- Methods can easily call each other within an RPC dispatch without needing to traverse the `mods[..].funs[..]` matrix each time. This is shown in the example with `avg` calls
  `sum`.
- Protected and private methods are not exposed but can be called by public methods -- more readily pull code out into separate methods.
- Argument errors are enforced more strictly with methods than with Proc blocks (on MRI 1.8.x at least).

I have an [expose branch](http://github.com/rtomayko/ernie/tree/expose) that adds `Ernie.expose` as described above.

**Comment by mojombo** [comment]
I like this approach way better than the DSL. I'm adding it into 1.2.0 and I will plan to deprecate the DSL in a future version.
