### ISSUE TITLE
Hard 15s timeout in port_wrapper:rpc

### ISSUE THREAD

**Issue by rtomayko** [mojombo/ernie#4]
There's a hardcoded 15 second timeout in the erlang layer of the server:

http://github.com/mojombo/ernie/blob/master/elib/port_wrapper.erl#L18-19

This limits the maximum possible timeout given in `BERTRPC::Service#timeout`, which we (github) have set to 10 minutes in background jobs. Also, calls fail with a "cannot read length header" on the client side (ruby BERTRPC only perhaps).

```
mod :test do
  fun :sleep do |duration|
    sleep duration
  end
end
```

And then in a client:

```
require 'bertrpc'
svc = BERTRPC::Service.new('localhost')
svc.call.test.sleep(20)
```

The client fails with `EOFError: end of file reached` when hitting the server directly or with something like `BERTRPC::ProtocolError: Unable to read length header from server.` when moving through ProxyMachine.

The server gives this as an error report:

```
=ERROR REPORT==== 21-Nov-2009::01:33:41 ===
Error in process <0.58.0> with exit value:
{{badmatch,{error,timed_out,<0.52.0>}},[{ernie_server,unsafe_process_now,2},{ernie_server,process_now,2}]}
```

I have a [detimeout](http://github.com/rtomayko/ernie/commit/detimeout) patch but I doubt it's going to be as simple as just removing it. We need some way of detecting stuck/defunct connections don't we?

**Comment by mojombo** [comment]
This was back-fixed in 0.4.1 (currently live on github.com) and is now included in 1.2.0.
