### ISSUE TITLE
ruby bin name hardcoded in elib/asset_pool.erl

### ISSUE THREAD

**Issue by badboy** [mojombo/ernie#5]
I wanted to try to work with ernie and reached some issues when starting it.

I installed the gem for my ruby v1.8.7
its binary is ruby18

after editing elib/asset_pool.erl to contain
    {asset, port_wrapper:wrap_link("ruby18 " ++ Handler), Token}

and adding "require 'rubygems'" to handler file it works.

Is there a way to handle this different?

**Comment by mojombo** [comment]
This will be configurable in Ernie 2.0. You can see the progress in the supernie branch right now. Take a look at the Readme.
